name = "hub"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "garyhub"
database_id = "3646bfb1-6936-427c-803f-85b3c13da1a9"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "garyhub"

[vars]
CLOUDFLARE_R2_PUBLIC_URL = "https://garyhub.4022.us"
