name = "your-worker-name"
main = "server.ts"
compatibility_date = "2026-04-13"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "your-d1-database-name"
database_id = "your-d1-database-id"
migrations_dir = "./migrations"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "your-r2-bucket-name"

[vars]
CLOUDFLARE_ZONE_ID = "your-zone-id"
CLOUDFLARE_ANALYTICS_API_TOKEN = "your-analytics-read-token"
